language: rust
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then admin/build-lcov ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install coveralls-lcov ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libclang-common-3.8-dev llvm-3.8-dev ; fi
script:
  - RUST_BACKTRACE=1 cargo test
  - RUST_BACKTRACE=1 cargo test --release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./admin/coverage          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls-lcov final.info ; fi
