[package]
name = "sct"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
description = "Certificate transparency SCT verification library"

[dependencies]
ring = "0.11"
untrusted = "0.5"
